{% set name = "support_developer" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/support_developer-{{ version }}.tar.gz
  sha256: 7739f63766b90480ee71d56c70ed8953500c48ab19e2782f867786642fce03d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - support_developer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LucaCappelletti94/support_developer
  summary: Package designed to centralize messages to support developers development work.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - dillonroach
